### ISSUE TITLE
arc_read() ignores `n_max = Inf`

### ISSUE THREAD

**Issue by JosiahParry** [R-ArcGIS/arcgislayers#170]
```r
res <- arc_read("https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_ZIP_Code_Points_analysis/FeatureServer/0", n_max = Inf)
````

compare this with setting `n_max = 1e10`

**Comment by elipousson** [comment]
I think I fixed this by always using the `n_feats` instead of `n_max` if n_max is infinite [`9c130e8` (#167)](https://github.com/R-ArcGIS/arcgislayers/pull/167/commits/9c130e83e445bdd2c805e87c0b21c57b4de5672b). After the refactor in that PR, I was actually getting an error with `n_max = Inf` which is why I touched this part.
