### ISSUE TITLE
Arcgislayers dependency installation failed

### ISSUE THREAD

**Issue by kkedji** [R-ArcGIS/arcgislayers#217]
**Describe the bug**
Hi, I am new to R programming and have been trying to install ArcGIS layers and found out it has been removed in CRAN. I tried 
to install the two archive version provided and still encountering the same error message despite all the workaround tried and all the pre-requisite (as far as I know) installed.

Here is the error message I got while trying to install the archive folder downloaded : install.packages("C:/Users/skkse/Downloads/arcgis_0.1.0.tar.gz", repos = NULL, type = "source")

Installing package into ‘C:/R_install/R-4.4.1/library’
(as ‘lib’ is unspecified)
ERROR: dependency 'arcgislayers' is not available for package 'arcgis'

The same message while trying to install here also : remotes::install_github("r-arcgis/arcgis", dependencies = TRUE).

I will appreciate any help on this.
Thank in advance.

**Comment by JosiahParry** [comment]
I am moving and cannot address CRAN's removal. I would recommend installing from r-universe instead.

install.packages("arcgis", repos = "https://r-arcgis.r-universe.dev")

This issue was reported solved by Uwe L. from CRAN on August 1st but it appears they decided to remove the packages without any warning. 

I am sorry you have encountered this.

**Comment by kkedji** [comment]
It's worked fine, thank you very much.

**Comment by JosiahParry** [comment]
Closing this. But it still is not resolved.
